export const PathRoutes = {
    HOME_PAGE: "/",
    DEPOSITS: "/deposits",
    ADMIN_LOGIN: "/admin-login",
    ADMIN_DASHBOARD: "/dashboard",
    SITE_MANAGER: "/site-manager",
    ADD_BANNER: "/add-banner",
    EDIT_BANNER: "/edit-banner/:id",
    PRODUCT_MANAGEMENT: "product-management",
    PRODUCT_VIEW: "/product/view",
    PRODUCT_EDIT: "/product/edit",
    ORDER_MANAGEMENT: "/order-management",
    ORDERS_DETAILS: "/viewordersdetails",
    USER_MANAGEMENT: "/user-management",
    USER_LIST: "/user-list",
    ADD_MEMBER: "/add-member",
    ADD_PRODUCT: "/add-product",
    ADD_CATEGORY: "/add-category",
    SUB_CATEGORY: "/sub-category",
    COMPANY_SETTINGS: "/company-settings",
    COMPANY_FORM: "/company-form",
    REWARDS: "/rewards",
    PACKAGES: "/packages",
    NOTIFICATION: "/notification",
    MESSAGE: "/message",
    PRODUCT_EDIT_ID: "/product/edit/:id",
    CATEGORY_CREATE: "/category/create",
    CATEGORY_EDIT_ID: "/category/edit/:id",
    USER_PROFILE_EDIT: "/user-profile/edit/:id",
    USER_PROFILE_DETAILS: "/user-profile/:id",


};