export const PathRoutes = {
    HOME_PAGE: "/",
    DEPOSITS: "/deposits", // Keeping for backward compatibility if needed, but prefer DEPOSIT_REQUESTS
    DEPOSIT_REQUESTS: "/deposit-requests",
    ADD_DEPOSIT: "/add-deposit",
    ADMIN_LOGIN: "/admin-login",
    ADMIN_DASHBOARD: "/dashboard",
    SITE_MANAGER: "/site-manager",
    ADD_BANNER: "/add-banner",
    EDIT_BANNER: "/edit-banner/:id",
    PRODUCT_MANAGEMENT: "product-management",
    PRODUCT_VIEW: "/product/view",
    PRODUCT_EDIT: "/product/edit",
    ORDER_MANAGEMENT: "/order-management",
    ORDERS_DETAILS: "/viewordersdetails",
    USER_MANAGEMENT: "/user-management",
    USER_LIST: "/user-list",
    ADD_MEMBER: "/add-member",
    ADD_PRODUCT: "/add-product",
    ADD_CATEGORY: "/add-category",
    SUB_CATEGORY: "/sub-category",
    COMPANY_SETTINGS: "/company-settings",
    COMPANY_FORM: "/company-form",
    REWARDS: "/rewards",
    PACKAGES: "/packages",
    NOTIFICATION: "/notification",
    MESSAGE: "/message",
    PRODUCT_EDIT_ID: "/product/edit/:id",
    CATEGORY_CREATE: "/category/create",
    CATEGORY_EDIT_ID: "/category/edit/:id",
    USER_PROFILE_EDIT: "/user-profile/edit/:id",
    USER_PROFILE_DETAILS: "/user-profile/:id",
    KYC_DETAILS: "/kyc-details",
    USER_PROFILE_EDIT: "/user-profile/edit/:id",
    USER_PROFILE_DETAILS: "/user-profile/:id",
    KYC_REQUESTS: "/kyc-requests",
    ADD_KYC: "/add-kyc",
    BANK_REQUESTS: "/bank-requests",
    BANK_DETAILS: "/bank-details/:id",
    ADD_BANK: "/add-bank",
    ADDRESS_REQUESTS: "/address-requests",
    ADD_ADDRESS: "/add-address",
    ADDRESS_DETAILS: "/address-details/:id",
    PRODUCT_VIEW_ID:"/product/view/:id",




};